{-# LANGUAGE OverloadedStrings #-}

import Control.Monad (forM, forM_, unless)
import Data.Char (toLower, toUpper)
import Data.List (sort)
import System.Directory
  ( doesDirectoryExist
  , listDirectory
  , createDirectoryIfMissing
  )
import System.FilePath ((</>))

srcDir :: FilePath
srcDir = "src"

appErrDir :: FilePath
appErrDir = srcDir </> "app_error"

appErrRs :: FilePath
appErrRs = srcDir </> "app_error.rs"

main :: IO ()
main = do
  ok <- doesDirectoryExist srcDir
  unless ok $ error "ERROR: ./src not found. Run from your Rust crate root."

  -- 1) create src/app_error/
  createDirectoryIfMissing True appErrDir

  -- discover immediate subdirectories of src/, excluding app_error
  entries <- listDirectory srcDir
  dirs <- fmap sort $ filterMDir entries
  let dirs' = filter (/= "app_error") dirs

  -- 2-3) create src/app_error/<dir>_error.rs
  forM_ dirs' $ \d -> do
    let filePath = appErrDir </> (d ++ "_error.rs")
        enumName = toPascal d ++ "Error"
    writeFile filePath (renderSubError d enumName)

  -- 4-7) create src/app_error.rs (module root of app_error)
  writeFile appErrRs (renderAppError dirs')

  putStrLn "✅ Generated:"
  putStrLn $ "  - " ++ appErrDir ++ " (contains *_error.rs)"
  putStrLn $ "  - " ++ appErrRs
  putStrLn $ "  - " ++ show (length dirs') ++ " error modules under src/app_error/<dir>_error.rs"
  putStrLn ""
  putStrLn "NOTE: Ensure Cargo.toml includes:"
  putStrLn "  thiserror = \"1\""
  putStrLn "  anyhow   = \"1\""

-- Helpers

filterMDir :: [FilePath] -> IO [FilePath]
filterMDir xs = do
  ys <- forM xs $ \x -> do
    let p = srcDir </> x
    isDir <- doesDirectoryExist p
    pure (if isDir then Just x else Nothing)
  pure [d | Just d <- ys]

toPascal :: String -> String
toPascal s = concatMap cap (splitOnDelims s)
  where
    cap ""     = ""
    cap (c:cs) = toUpper c : map toLower cs

splitOnDelims :: String -> [String]
splitOnDelims = go [] []
  where
    isDelim c = c == '_' || c == '-'
    go cur acc [] =
      reverse (if null cur then acc else reverse cur : acc)
    go cur acc (c:cs)
      | isDelim c =
          if null cur
            then go [] acc cs
            else go [] (reverse cur : acc) cs
      | otherwise = go (c:cur) acc cs

renderSubError :: String -> String -> String
renderSubError dir enumName =
  unlines
    [ "use thiserror::Error;"
    , ""
    , "#[derive(Debug, Error)]"
    , "pub enum " ++ enumName ++ " {"
    , "    #[error(\"" ++ escape dir ++ " error: {0}\")]"
    , "    Message(String),"
    , "}"
    ]

renderAppError :: [String] -> String
renderAppError dirs =
  unlines $
    [ "//! Generated by gen_app_error.hs"
    , "use thiserror::Error;"
    , ""
    ]
    ++ concatMap renderModule dirs
    ++ concatMap renderReExport dirs
    ++ [ ""
       , "#[derive(Debug, Error)]"
       , "pub enum AppError {"
       ]
    ++ concatMap renderVariant dirs
    ++ [ "    #[error(transparent)]"
       , "    Anyhow(#[from] anyhow::Error),"
       , "}"
       , ""
       , "impl From<AppError> for anyhow::Error {"
       , "    fn from(e: AppError) -> Self {"
       , "        match e {"
       , "            AppError::Anyhow(inner) => inner,"
       , "            other => anyhow::Error::new(other),"
       , "        }"
       , "    }"
       , "}"
       ]
  where
    -- Since modules are under src/app_error/, no #[path] needed.
    -- Module name: <dir>_error  => file: src/app_error/<dir>_error.rs
    renderModule d =
      [ "pub mod " ++ d ++ "_error;"
      , ""
      ]

    renderReExport d =
      [ "pub use " ++ d ++ "_error::" ++ toPascal d ++ "Error;"
      ]

    renderVariant d =
      let enumName    = toPascal d ++ "Error"
          variantName = toPascal d
       in [ "    #[error(transparent)]"
          , "    " ++ variantName ++ "(#[from] " ++ enumName ++ "),"
          ]

escape :: String -> String
escape = concatMap esc
  where
    esc '"'  = "\\\""
    esc '\\' = "\\\\"
    esc c    = [c]
