// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: v1/service.proto

package gateflowv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	ExpireAt      string                 `protobuf:"bytes,3,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LoginResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *LoginResponse) GetExpireAt() string {
	if x != nil {
		return x.ExpireAt
	}
	return ""
}

type AddAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	TargetUrl     string                 `protobuf:"bytes,2,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	MountPath     string                 `protobuf:"bytes,3,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	UpstreamPath  string                 `protobuf:"bytes,4,opt,name=upstream_path,json=upstreamPath,proto3" json:"upstream_path,omitempty"`
	Secret        *string                `protobuf:"bytes,5,opt,name=secret,proto3,oneof" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAppRequest) Reset() {
	*x = AddAppRequest{}
	mi := &file_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAppRequest) ProtoMessage() {}

func (x *AddAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAppRequest.ProtoReflect.Descriptor instead.
func (*AddAppRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *AddAppRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *AddAppRequest) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *AddAppRequest) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *AddAppRequest) GetUpstreamPath() string {
	if x != nil {
		return x.UpstreamPath
	}
	return ""
}

func (x *AddAppRequest) GetSecret() string {
	if x != nil && x.Secret != nil {
		return *x.Secret
	}
	return ""
}

type AddAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	TargetUrl     string                 `protobuf:"bytes,2,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	Secret        string                 `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAppResponse) Reset() {
	*x = AddAppResponse{}
	mi := &file_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAppResponse) ProtoMessage() {}

func (x *AddAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAppResponse.ProtoReflect.Descriptor instead.
func (*AddAppResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *AddAppResponse) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *AddAppResponse) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *AddAppResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type ApproveAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppIdentify   string                 `protobuf:"bytes,1,opt,name=app_identify,json=appIdentify,proto3" json:"app_identify,omitempty"`
	IdentifyType  string                 `protobuf:"bytes,2,opt,name=identify_type,json=identifyType,proto3" json:"identify_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveAppRequest) Reset() {
	*x = ApproveAppRequest{}
	mi := &file_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveAppRequest) ProtoMessage() {}

func (x *ApproveAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveAppRequest.ProtoReflect.Descriptor instead.
func (*ApproveAppRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *ApproveAppRequest) GetAppIdentify() string {
	if x != nil {
		return x.AppIdentify
	}
	return ""
}

func (x *ApproveAppRequest) GetIdentifyType() string {
	if x != nil {
		return x.IdentifyType
	}
	return ""
}

type ApproveAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveAppResponse) Reset() {
	*x = ApproveAppResponse{}
	mi := &file_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveAppResponse) ProtoMessage() {}

func (x *ApproveAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveAppResponse.ProtoReflect.Descriptor instead.
func (*ApproveAppResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *ApproveAppResponse) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ApproveAppResponse) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *ApproveAppResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DisableAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppIdentify   string                 `protobuf:"bytes,1,opt,name=app_identify,json=appIdentify,proto3" json:"app_identify,omitempty"`
	IdentifyType  string                 `protobuf:"bytes,2,opt,name=identify_type,json=identifyType,proto3" json:"identify_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableAppRequest) Reset() {
	*x = DisableAppRequest{}
	mi := &file_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableAppRequest) ProtoMessage() {}

func (x *DisableAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableAppRequest.ProtoReflect.Descriptor instead.
func (*DisableAppRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *DisableAppRequest) GetAppIdentify() string {
	if x != nil {
		return x.AppIdentify
	}
	return ""
}

func (x *DisableAppRequest) GetIdentifyType() string {
	if x != nil {
		return x.IdentifyType
	}
	return ""
}

type DisableAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableAppResponse) Reset() {
	*x = DisableAppResponse{}
	mi := &file_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableAppResponse) ProtoMessage() {}

func (x *DisableAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableAppResponse.ProtoReflect.Descriptor instead.
func (*DisableAppResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *DisableAppResponse) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *DisableAppResponse) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *DisableAppResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RouteUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	MountPath     string                 `protobuf:"bytes,2,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	UpstreamPath  string                 `protobuf:"bytes,3,opt,name=upstream_path,json=upstreamPath,proto3" json:"upstream_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteUpdateRequest) Reset() {
	*x = RouteUpdateRequest{}
	mi := &file_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteUpdateRequest) ProtoMessage() {}

func (x *RouteUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteUpdateRequest.ProtoReflect.Descriptor instead.
func (*RouteUpdateRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *RouteUpdateRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *RouteUpdateRequest) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *RouteUpdateRequest) GetUpstreamPath() string {
	if x != nil {
		return x.UpstreamPath
	}
	return ""
}

type RouteUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	MountPath     string                 `protobuf:"bytes,4,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	UpstreamPath  string                 `protobuf:"bytes,5,opt,name=upstream_path,json=upstreamPath,proto3" json:"upstream_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteUpdateResponse) Reset() {
	*x = RouteUpdateResponse{}
	mi := &file_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteUpdateResponse) ProtoMessage() {}

func (x *RouteUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteUpdateResponse.ProtoReflect.Descriptor instead.
func (*RouteUpdateResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *RouteUpdateResponse) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *RouteUpdateResponse) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *RouteUpdateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RouteUpdateResponse) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *RouteUpdateResponse) GetUpstreamPath() string {
	if x != nil {
		return x.UpstreamPath
	}
	return ""
}

type AppList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	TargetUrl     string                 `protobuf:"bytes,3,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	MountPath     string                 `protobuf:"bytes,4,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	UpstreamPath  string                 `protobuf:"bytes,5,opt,name=upstream_path,json=upstreamPath,proto3" json:"upstream_path,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppList) Reset() {
	*x = AppList{}
	mi := &file_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppList) ProtoMessage() {}

func (x *AppList) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppList.ProtoReflect.Descriptor instead.
func (*AppList) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *AppList) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AppList) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *AppList) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *AppList) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *AppList) GetUpstreamPath() string {
	if x != nil {
		return x.UpstreamPath
	}
	return ""
}

func (x *AppList) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{11}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*AppList             `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListResponse) GetList() []*AppList {
	if x != nil {
		return x.List
	}
	return nil
}

type ShowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppIdentify   string                 `protobuf:"bytes,1,opt,name=app_identify,json=appIdentify,proto3" json:"app_identify,omitempty"`
	IdentifyType  string                 `protobuf:"bytes,2,opt,name=identify_type,json=identifyType,proto3" json:"identify_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowRequest) Reset() {
	*x = ShowRequest{}
	mi := &file_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowRequest) ProtoMessage() {}

func (x *ShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowRequest.ProtoReflect.Descriptor instead.
func (*ShowRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *ShowRequest) GetAppIdentify() string {
	if x != nil {
		return x.AppIdentify
	}
	return ""
}

func (x *ShowRequest) GetIdentifyType() string {
	if x != nil {
		return x.IdentifyType
	}
	return ""
}

type ShowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *AppList               `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowResponse) Reset() {
	*x = ShowResponse{}
	mi := &file_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowResponse) ProtoMessage() {}

func (x *ShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowResponse.ProtoReflect.Descriptor instead.
func (*ShowResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *ShowResponse) GetApp() *AppList {
	if x != nil {
		return x.App
	}
	return nil
}

type NodeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	HealthUrl     string                 `protobuf:"bytes,3,opt,name=health_url,json=healthUrl,proto3" json:"health_url,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ExpectStatus  string                 `protobuf:"bytes,5,opt,name=expect_status,json=expectStatus,proto3" json:"expect_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeList) Reset() {
	*x = NodeList{}
	mi := &file_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeList) ProtoMessage() {}

func (x *NodeList) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeList.ProtoReflect.Descriptor instead.
func (*NodeList) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *NodeList) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *NodeList) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *NodeList) GetHealthUrl() string {
	if x != nil {
		return x.HealthUrl
	}
	return ""
}

func (x *NodeList) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeList) GetExpectStatus() string {
	if x != nil {
		return x.ExpectStatus
	}
	return ""
}

type NodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRequest) Reset() {
	*x = NodeRequest{}
	mi := &file_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRequest) ProtoMessage() {}

func (x *NodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRequest.ProtoReflect.Descriptor instead.
func (*NodeRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{16}
}

type NodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*NodeList            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeResponse) Reset() {
	*x = NodeResponse{}
	mi := &file_v1_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResponse) ProtoMessage() {}

func (x *NodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResponse.ProtoReflect.Descriptor instead.
func (*NodeResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_proto_rawDescGZIP(), []int{17}
}

func (x *NodeResponse) GetList() []*NodeList {
	if x != nil {
		return x.List
	}
	return nil
}

var File_v1_service_proto protoreflect.FileDescriptor

const file_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x10v1/service.proto\x12\vgateflow.v1\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"c\n" +
	"\rLoginResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12\x1b\n" +
	"\texpire_at\x18\x03 \x01(\tR\bexpireAt\"\xb5\x01\n" +
	"\rAddAppRequest\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x1d\n" +
	"\n" +
	"target_url\x18\x02 \x01(\tR\ttargetUrl\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x03 \x01(\tR\tmountPath\x12#\n" +
	"\rupstream_path\x18\x04 \x01(\tR\fupstreamPath\x12\x1b\n" +
	"\x06secret\x18\x05 \x01(\tH\x00R\x06secret\x88\x01\x01B\t\n" +
	"\a_secret\"b\n" +
	"\x0eAddAppResponse\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x1d\n" +
	"\n" +
	"target_url\x18\x02 \x01(\tR\ttargetUrl\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\tR\x06secret\"[\n" +
	"\x11ApproveAppRequest\x12!\n" +
	"\fapp_identify\x18\x01 \x01(\tR\vappIdentify\x12#\n" +
	"\ridentify_type\x18\x02 \x01(\tR\fidentifyType\"^\n" +
	"\x12ApproveAppResponse\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"[\n" +
	"\x11DisableAppRequest\x12!\n" +
	"\fapp_identify\x18\x01 \x01(\tR\vappIdentify\x12#\n" +
	"\ridentify_type\x18\x02 \x01(\tR\fidentifyType\"^\n" +
	"\x12DisableAppResponse\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"s\n" +
	"\x12RouteUpdateRequest\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x02 \x01(\tR\tmountPath\x12#\n" +
	"\rupstream_path\x18\x03 \x01(\tR\fupstreamPath\"\xa3\x01\n" +
	"\x13RouteUpdateResponse\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x04 \x01(\tR\tmountPath\x12#\n" +
	"\rupstream_path\x18\x05 \x01(\tR\fupstreamPath\"\xb6\x01\n" +
	"\aAppList\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x1d\n" +
	"\n" +
	"target_url\x18\x03 \x01(\tR\ttargetUrl\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x04 \x01(\tR\tmountPath\x12#\n" +
	"\rupstream_path\x18\x05 \x01(\tR\fupstreamPath\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\r\n" +
	"\vListRequest\"8\n" +
	"\fListResponse\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.gateflow.v1.AppListR\x04list\"U\n" +
	"\vShowRequest\x12!\n" +
	"\fapp_identify\x18\x01 \x01(\tR\vappIdentify\x12#\n" +
	"\ridentify_type\x18\x02 \x01(\tR\fidentifyType\"6\n" +
	"\fShowResponse\x12&\n" +
	"\x03app\x18\x01 \x01(\v2\x14.gateflow.v1.AppListR\x03app\"\x98\x01\n" +
	"\bNodeList\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x1d\n" +
	"\n" +
	"health_url\x18\x03 \x01(\tR\thealthUrl\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12#\n" +
	"\rexpect_status\x18\x05 \x01(\tR\fexpectStatus\"\r\n" +
	"\vNodeRequest\"9\n" +
	"\fNodeResponse\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.gateflow.v1.NodeListR\x04list2\xbf\x04\n" +
	"\x0fGateflowService\x12>\n" +
	"\x05Login\x12\x19.gateflow.v1.LoginRequest\x1a\x1a.gateflow.v1.LoginResponse\x12A\n" +
	"\x06AddApp\x12\x1a.gateflow.v1.AddAppRequest\x1a\x1b.gateflow.v1.AddAppResponse\x12M\n" +
	"\n" +
	"ApproveApp\x12\x1e.gateflow.v1.ApproveAppRequest\x1a\x1f.gateflow.v1.ApproveAppResponse\x12M\n" +
	"\n" +
	"DisableApp\x12\x1e.gateflow.v1.DisableAppRequest\x1a\x1f.gateflow.v1.DisableAppResponse\x12P\n" +
	"\vRouteUpdate\x12\x1f.gateflow.v1.RouteUpdateRequest\x1a .gateflow.v1.RouteUpdateResponse\x12;\n" +
	"\x04List\x12\x18.gateflow.v1.ListRequest\x1a\x19.gateflow.v1.ListResponse\x12;\n" +
	"\x04Show\x12\x18.gateflow.v1.ShowRequest\x1a\x19.gateflow.v1.ShowResponse\x12?\n" +
	"\bNodeList\x12\x18.gateflow.v1.NodeRequest\x1a\x19.gateflow.v1.NodeResponseB\x16Z\x14client/v1;gateflowv1b\x06proto3"

var (
	file_v1_service_proto_rawDescOnce sync.Once
	file_v1_service_proto_rawDescData []byte
)

func file_v1_service_proto_rawDescGZIP() []byte {
	file_v1_service_proto_rawDescOnce.Do(func() {
		file_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_service_proto_rawDesc), len(file_v1_service_proto_rawDesc)))
	})
	return file_v1_service_proto_rawDescData
}

var file_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_v1_service_proto_goTypes = []any{
	(*LoginRequest)(nil),        // 0: gateflow.v1.LoginRequest
	(*LoginResponse)(nil),       // 1: gateflow.v1.LoginResponse
	(*AddAppRequest)(nil),       // 2: gateflow.v1.AddAppRequest
	(*AddAppResponse)(nil),      // 3: gateflow.v1.AddAppResponse
	(*ApproveAppRequest)(nil),   // 4: gateflow.v1.ApproveAppRequest
	(*ApproveAppResponse)(nil),  // 5: gateflow.v1.ApproveAppResponse
	(*DisableAppRequest)(nil),   // 6: gateflow.v1.DisableAppRequest
	(*DisableAppResponse)(nil),  // 7: gateflow.v1.DisableAppResponse
	(*RouteUpdateRequest)(nil),  // 8: gateflow.v1.RouteUpdateRequest
	(*RouteUpdateResponse)(nil), // 9: gateflow.v1.RouteUpdateResponse
	(*AppList)(nil),             // 10: gateflow.v1.AppList
	(*ListRequest)(nil),         // 11: gateflow.v1.ListRequest
	(*ListResponse)(nil),        // 12: gateflow.v1.ListResponse
	(*ShowRequest)(nil),         // 13: gateflow.v1.ShowRequest
	(*ShowResponse)(nil),        // 14: gateflow.v1.ShowResponse
	(*NodeList)(nil),            // 15: gateflow.v1.NodeList
	(*NodeRequest)(nil),         // 16: gateflow.v1.NodeRequest
	(*NodeResponse)(nil),        // 17: gateflow.v1.NodeResponse
}
var file_v1_service_proto_depIdxs = []int32{
	10, // 0: gateflow.v1.ListResponse.list:type_name -> gateflow.v1.AppList
	10, // 1: gateflow.v1.ShowResponse.app:type_name -> gateflow.v1.AppList
	15, // 2: gateflow.v1.NodeResponse.list:type_name -> gateflow.v1.NodeList
	0,  // 3: gateflow.v1.GateflowService.Login:input_type -> gateflow.v1.LoginRequest
	2,  // 4: gateflow.v1.GateflowService.AddApp:input_type -> gateflow.v1.AddAppRequest
	4,  // 5: gateflow.v1.GateflowService.ApproveApp:input_type -> gateflow.v1.ApproveAppRequest
	6,  // 6: gateflow.v1.GateflowService.DisableApp:input_type -> gateflow.v1.DisableAppRequest
	8,  // 7: gateflow.v1.GateflowService.RouteUpdate:input_type -> gateflow.v1.RouteUpdateRequest
	11, // 8: gateflow.v1.GateflowService.List:input_type -> gateflow.v1.ListRequest
	13, // 9: gateflow.v1.GateflowService.Show:input_type -> gateflow.v1.ShowRequest
	16, // 10: gateflow.v1.GateflowService.NodeList:input_type -> gateflow.v1.NodeRequest
	1,  // 11: gateflow.v1.GateflowService.Login:output_type -> gateflow.v1.LoginResponse
	3,  // 12: gateflow.v1.GateflowService.AddApp:output_type -> gateflow.v1.AddAppResponse
	5,  // 13: gateflow.v1.GateflowService.ApproveApp:output_type -> gateflow.v1.ApproveAppResponse
	7,  // 14: gateflow.v1.GateflowService.DisableApp:output_type -> gateflow.v1.DisableAppResponse
	9,  // 15: gateflow.v1.GateflowService.RouteUpdate:output_type -> gateflow.v1.RouteUpdateResponse
	12, // 16: gateflow.v1.GateflowService.List:output_type -> gateflow.v1.ListResponse
	14, // 17: gateflow.v1.GateflowService.Show:output_type -> gateflow.v1.ShowResponse
	17, // 18: gateflow.v1.GateflowService.NodeList:output_type -> gateflow.v1.NodeResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_v1_service_proto_init() }
func file_v1_service_proto_init() {
	if File_v1_service_proto != nil {
		return
	}
	file_v1_service_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_service_proto_rawDesc), len(file_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_service_proto_goTypes,
		DependencyIndexes: file_v1_service_proto_depIdxs,
		MessageInfos:      file_v1_service_proto_msgTypes,
	}.Build()
	File_v1_service_proto = out.File
	file_v1_service_proto_goTypes = nil
	file_v1_service_proto_depIdxs = nil
}
