// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: v1/service.proto

package gateflowv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GateflowService_Login_FullMethodName       = "/gateflow.v1.GateflowService/Login"
	GateflowService_AddApp_FullMethodName      = "/gateflow.v1.GateflowService/AddApp"
	GateflowService_ApproveApp_FullMethodName  = "/gateflow.v1.GateflowService/ApproveApp"
	GateflowService_DisableApp_FullMethodName  = "/gateflow.v1.GateflowService/DisableApp"
	GateflowService_RouteUpdate_FullMethodName = "/gateflow.v1.GateflowService/RouteUpdate"
	GateflowService_List_FullMethodName        = "/gateflow.v1.GateflowService/List"
	GateflowService_Show_FullMethodName        = "/gateflow.v1.GateflowService/Show"
	GateflowService_NodeList_FullMethodName    = "/gateflow.v1.GateflowService/NodeList"
)

// GateflowServiceClient is the client API for GateflowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GateflowServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	AddApp(ctx context.Context, in *AddAppRequest, opts ...grpc.CallOption) (*AddAppResponse, error)
	ApproveApp(ctx context.Context, in *ApproveAppRequest, opts ...grpc.CallOption) (*ApproveAppResponse, error)
	DisableApp(ctx context.Context, in *DisableAppRequest, opts ...grpc.CallOption) (*DisableAppResponse, error)
	RouteUpdate(ctx context.Context, in *RouteUpdateRequest, opts ...grpc.CallOption) (*RouteUpdateResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Show(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (*ShowResponse, error)
	NodeList(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*NodeResponse, error)
}

type gateflowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGateflowServiceClient(cc grpc.ClientConnInterface) GateflowServiceClient {
	return &gateflowServiceClient{cc}
}

func (c *gateflowServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, GateflowService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateflowServiceClient) AddApp(ctx context.Context, in *AddAppRequest, opts ...grpc.CallOption) (*AddAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAppResponse)
	err := c.cc.Invoke(ctx, GateflowService_AddApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateflowServiceClient) ApproveApp(ctx context.Context, in *ApproveAppRequest, opts ...grpc.CallOption) (*ApproveAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveAppResponse)
	err := c.cc.Invoke(ctx, GateflowService_ApproveApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateflowServiceClient) DisableApp(ctx context.Context, in *DisableAppRequest, opts ...grpc.CallOption) (*DisableAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableAppResponse)
	err := c.cc.Invoke(ctx, GateflowService_DisableApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateflowServiceClient) RouteUpdate(ctx context.Context, in *RouteUpdateRequest, opts ...grpc.CallOption) (*RouteUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteUpdateResponse)
	err := c.cc.Invoke(ctx, GateflowService_RouteUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateflowServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, GateflowService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateflowServiceClient) Show(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (*ShowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowResponse)
	err := c.cc.Invoke(ctx, GateflowService_Show_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateflowServiceClient) NodeList(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, GateflowService_NodeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GateflowServiceServer is the server API for GateflowService service.
// All implementations must embed UnimplementedGateflowServiceServer
// for forward compatibility.
type GateflowServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	AddApp(context.Context, *AddAppRequest) (*AddAppResponse, error)
	ApproveApp(context.Context, *ApproveAppRequest) (*ApproveAppResponse, error)
	DisableApp(context.Context, *DisableAppRequest) (*DisableAppResponse, error)
	RouteUpdate(context.Context, *RouteUpdateRequest) (*RouteUpdateResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Show(context.Context, *ShowRequest) (*ShowResponse, error)
	NodeList(context.Context, *NodeRequest) (*NodeResponse, error)
	mustEmbedUnimplementedGateflowServiceServer()
}

// UnimplementedGateflowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGateflowServiceServer struct{}

func (UnimplementedGateflowServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedGateflowServiceServer) AddApp(context.Context, *AddAppRequest) (*AddAppResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddApp not implemented")
}
func (UnimplementedGateflowServiceServer) ApproveApp(context.Context, *ApproveAppRequest) (*ApproveAppResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveApp not implemented")
}
func (UnimplementedGateflowServiceServer) DisableApp(context.Context, *DisableAppRequest) (*DisableAppResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableApp not implemented")
}
func (UnimplementedGateflowServiceServer) RouteUpdate(context.Context, *RouteUpdateRequest) (*RouteUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RouteUpdate not implemented")
}
func (UnimplementedGateflowServiceServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedGateflowServiceServer) Show(context.Context, *ShowRequest) (*ShowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Show not implemented")
}
func (UnimplementedGateflowServiceServer) NodeList(context.Context, *NodeRequest) (*NodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeList not implemented")
}
func (UnimplementedGateflowServiceServer) mustEmbedUnimplementedGateflowServiceServer() {}
func (UnimplementedGateflowServiceServer) testEmbeddedByValue()                         {}

// UnsafeGateflowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GateflowServiceServer will
// result in compilation errors.
type UnsafeGateflowServiceServer interface {
	mustEmbedUnimplementedGateflowServiceServer()
}

func RegisterGateflowServiceServer(s grpc.ServiceRegistrar, srv GateflowServiceServer) {
	// If the following call panics, it indicates UnimplementedGateflowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GateflowService_ServiceDesc, srv)
}

func _GateflowService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateflowServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateflowService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateflowServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateflowService_AddApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateflowServiceServer).AddApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateflowService_AddApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateflowServiceServer).AddApp(ctx, req.(*AddAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateflowService_ApproveApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateflowServiceServer).ApproveApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateflowService_ApproveApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateflowServiceServer).ApproveApp(ctx, req.(*ApproveAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateflowService_DisableApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateflowServiceServer).DisableApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateflowService_DisableApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateflowServiceServer).DisableApp(ctx, req.(*DisableAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateflowService_RouteUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateflowServiceServer).RouteUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateflowService_RouteUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateflowServiceServer).RouteUpdate(ctx, req.(*RouteUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateflowService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateflowServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateflowService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateflowServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateflowService_Show_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateflowServiceServer).Show(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateflowService_Show_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateflowServiceServer).Show(ctx, req.(*ShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateflowService_NodeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateflowServiceServer).NodeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateflowService_NodeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateflowServiceServer).NodeList(ctx, req.(*NodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GateflowService_ServiceDesc is the grpc.ServiceDesc for GateflowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GateflowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateflow.v1.GateflowService",
	HandlerType: (*GateflowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _GateflowService_Login_Handler,
		},
		{
			MethodName: "AddApp",
			Handler:    _GateflowService_AddApp_Handler,
		},
		{
			MethodName: "ApproveApp",
			Handler:    _GateflowService_ApproveApp_Handler,
		},
		{
			MethodName: "DisableApp",
			Handler:    _GateflowService_DisableApp_Handler,
		},
		{
			MethodName: "RouteUpdate",
			Handler:    _GateflowService_RouteUpdate_Handler,
		},
		{
			MethodName: "List",
			Handler:    _GateflowService_List_Handler,
		},
		{
			MethodName: "Show",
			Handler:    _GateflowService_Show_Handler,
		},
		{
			MethodName: "NodeList",
			Handler:    _GateflowService_NodeList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/service.proto",
}
